#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

sudo apt-get -y install nginx
# 1 Return a page with 'Hello World' text
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# redirects /redirect_me to another page
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# creates custom 404 html page contaning a string
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx restart

