#!/usr/bin/env bash
# add Custom Header 'X-Served-By' with hostname as value

# install nginx
sudo apt-get -y install nginx
# update contents of index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# redirects /redirect_me to another page
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default

# creates custom 404 html page contaning a string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "47s|.*| \n\terror_page 404 /error404.html;\n|" /etc/nginx/sites-enabled/default

# add custom header
sudo sed -i '52 a \\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
