#!/usr/bin/env bash
# add Custom Header 'X-Served-By' with hostname as value

# install nginx
sudo apt-get -y install nginx
# update contents of index file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
# add custom header
sudo sed -i '52 a \\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
