#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely. With a sleep 2 in between each iterationI am invincible!!! when receiving a SIGTERM signal

i="I am Invincible!!!"

function func(){
 echo "$i"
}

function func2(){
   trap func SIGTERM
}

func2
while true; do
echo "To infinity and beyond"
sleep 2 
done
