#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5


for i in {1..100}
do
  if [ $((i % 5)) -eq 0 ] && [ $((i % 3)) -eq 0 ]
  then
     echo "fizzbuzz"
  elif [ $((i % 3)) -eq 0 ]
  then
      echo "fizz"
  elif [ $((i % 5)) -eq 0 ]
  then
      echo "buzz"
  else
      echo "$i"
  fi 
done
