#!/usr/bin/env bash
# Using what you did in the previous exercise, write a Bash script that groups visitors by IP and HTTP status code, and displays this data.

# Requirements:
#  The exact format must be:
#  OCCURENCE_NUMBER IP HTTP_CODE
#  In list format
#  Ordered from the greatest to the lowest number of occurrences

awk '{print $1" "$9}' apache-access.log | sort | uniq -c | sort -nr

