#!/usr/bin/env bash
# configures an Ubuntu server with the following requirements. 1)localhost resolves to 127.0.0.2 2)facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
