#!/usr/bin/env bash
# runs nginx as 'nginx' user 
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
pkill -f "apache2"
sudo -u nginx service nginx restart
