#!/usr/bin/env bash
# Bash script that runs nginx as nginx user
pkill -f "apache2"
sed -i "s/www-data/nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
